sonarcloud-check:
  image: maven:3-openjdk-17
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - cd backend/tharseo && mvn verify sonar:sonar
  only:
    - merge_requests
    - main
    - develop
