# variables:
#   SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
#   GIT_DEPTH: "0"
#   image: maven:3-openjdk-17
#   cache:
#     key: "${CI_JOB_NAME}"
#     paths:
#       - .sonar/cache
#   script:
#     - cd backend/tharseo && mvn verify sonar:sonar -Dsonar.projectKey=dsmfatec_tharseo-automation-trader
#   only:
#     - merge_requests
#     - main
#     - develop
