name: Semantic Versioning and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Bump Version and Create Release
        id: bump_version
        uses: mathieudutour/github-tag-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
             default_bump: patch 

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
              tag_name: ${{ steps.bump_version.outputs.new_tag }}
              release_name: Release ${{ steps.bump_version.outputs.new_tag }}
              body: Automatic release created by GitHub Actions.
              draft: false
              prerelease: false
    