name: Semantic Versioning and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording:  'add,Adds,new'
          major-wording:  'MAJOR,cut-major'
          patch-wording:  'patch,fixes'    
          rc-wording:     'RELEASE,alpha'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
              tag_name: ${{ steps.version-bump.outputs.newTag }}
              release_name: Release ${{ steps.version-bump.outputs.newTag }} 
              body: Automatic release created by GitHub Actions.
              draft: false
              prerelease: false
    