name: Deploy Java App to Azure VMM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17' 
        distribution: 'temurin'

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: 74.235.240.231
        username: richardguedes
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd backend/tharseo
          docker pull richardguedesrib/tharseo:latest
          docker run -d -p 8080:8080 richardguedesrib/tharseo:latest