name: Deploy Java App to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17' 
        distribution: 'temurin'

    - name: Build and Deploy
      run: |
       
        cd backend/tharseo && mvn clean package
        scp -o StrictHostKeyChecking=no ${{ secrets.SSH_PRIVATE_KEY }} target/tharseo-0.0.1-SNAPSHOT.jar richardguedes@74.235.240.231:/home/richardguedes/tharseo
        ssh richardguedes@74.235.240.231 "java -jar /home/richardguedes/tharseo/tharseo-0.0.1-SNAPSHOT.jar &"