name: Deploy Report to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17' 
        distribution: 'temurin'
    
    - name: Run Tharseo Tests 
      run:  cd backend/tharseo && mvn verify

    - name: Move report to docs directory
      run:  mv target/dependency-check-report.html docs/

    - name: Commit and push report to GitHub Pages
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update report"
        repository: ${{ github.repository }}
        branch: gh-pages
        files: docs/relatorio.html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
