name: TESTE ZAP


on:
    push:
      branches:
        - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
            target: 'http://104.45.141.47/'